name: 'Check Changelog'
description: 'Check if a changelog has changed, and a header has been specified'
inputs:
  header:
    description: 'The header to search for in the changelog'
    required: true
    default: '## Recent Changes'
  file:
    description: 'The path to the changelog'
    required: true
    default: 'CHANGELOG.md'
  token:
    description: 'The GitHub token'
    required: true
outputs:
  changed:
    description: 'If the changelog file was changed in the PR diff'
  header:
    description: 'If the required header was found'
runs:
  using: 'node12'
  main: 'index.js'
